esphome:
  name: watt-meter
  friendly_name: Watt Meter

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

logger:
  hardware_uart: USB_CDC

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  output_power: 17dB
  manual_ip:
    static_ip: 192.168.0.10  
    gateway: 192.168.0.1    
    subnet: 255.255.255.0


sensor:
  - platform: adc
    pin: GPIO1
    id: source_sensor
    attenuation: 12db

  - platform: ct_clamp
    sensor: source_sensor
    name: "Server Proud"
    id: server_amps
    update_interval: 5s
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 1.0 -> 16.8
      
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1

      - lambda: if (x < 0.08) return 0; else return x;

  - platform: template
    name: "Server Výkon"
    id: server_watts
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    accuracy_decimals: 1
    lambda: return id(server_amps).state * 230.0;
    update_interval: 5s
