esphome:
  name: terrariumcontroller
  on_boot:
    priority: 800
    then:
      - switch.turn_off: pump_relay
      - switch.turn_off: fan_relay
      - switch.turn_off: lamp_relay
      - switch.turn_off: cooler_relay
      - delay: 30s

esp32:
  board: esp32dev
  flash_size: 4MB
  framework:
    type: arduino

logger:

api:
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  output_power: 17dB
  manual_ip:
    static_ip: 192.168.0.12
    gateway: 192.168.0.1
    subnet: 255.255.255.0

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Prague

globals:
  - id: high_humidity_counter
    type: int
    restore_value: false
    initial_value: '0'

sensor:
  - platform: dht
    pin: GPIO14
    model: DHT11
    temperature:
      id: terrarium_temperature
      name: "Terrarium Temperature"
      unit_of_measurement: "°C"
      filters:
        - exponential_moving_average:
            alpha: 0.8   # Minimal smoothing (80% weight on new data)
            send_every: 1 # Update state every 5s
    humidity: 
      id: terrarium_humidity
      name: "Terrarium Humidity"
      unit_of_measurement: "%"
      filters:
        - exponential_moving_average:
            alpha: 0.8   # Minimal smoothing
            send_every: 1 # Update state every 5s
    update_interval: 5s

switch:
  - platform: gpio
    pin: GPIO27
    id: pump_relay
    name: "Pump Relay"
    inverted: true
  - platform: gpio
    pin: GPIO32
    id: fan_relay
    name: "Fan Relay"
    inverted: true
  - platform: gpio
    pin: GPIO33
    id: lamp_relay
    name: "Lamp Relay"
    inverted: true
  - platform: gpio
    pin: GPIO12
    id: cooler_relay
    name: "Cooler Relay"
    inverted: true

interval:
  - interval: 20s
    then:
      - lambda: |-
          // === 1. GET CURRENT STATE ===
          if (!id(sntp_time).now().is_valid()) {
            ESP_LOGD("main", "SNTP time not valid yet, skipping loop.");
            return;
          }
          if (id(terrarium_temperature).state == NAN || id(terrarium_humidity).state == NAN) {
            ESP_LOGD("main", "Sensor state is NAN, skipping loop.");
            return;
          }

          float t = id(terrarium_temperature).state;
          float h = id(terrarium_humidity).state;
          float current_hour = id(sntp_time).now().hour + (id(sntp_time).now().minute / 60.0);
          int hour_int = id(sntp_time).now().hour;
          int minute_int = id(sntp_time).now().minute;
          bool is_night = (hour_int >= 20 || hour_int < 8);
          bool is_day = !is_night;
          bool is_evening_spike = (hour_int == 20 && minute_int < 10);

          // === 2. GRADUAL TEMPERATURE TARGET ===
          const float PEAK_TEMP = 26.0;
          const float PEAK_HOUR = 14.0;
          const float LOW_TEMP = 18.0;
          const float LOW_HOUR = 3.0;

          float t_target = 0.0;

          if (current_hour >= LOW_HOUR && current_hour < PEAK_HOUR) {
            float hours_into_ramp = current_hour - LOW_HOUR;
            float total_ramp_hours = PEAK_HOUR - LOW_HOUR;
            float temp_range = PEAK_TEMP - LOW_TEMP;
            t_target = LOW_TEMP + (hours_into_ramp / total_ramp_hours) * temp_range;
          } else {
            float hours_past_peak;
            if (current_hour >= PEAK_HOUR) {
              hours_past_peak = current_hour - PEAK_HOUR;
            } else {
              hours_past_peak = current_hour + (24.0 - PEAK_HOUR);
            }
            float total_ramp_hours = (24.0 - PEAK_HOUR) + LOW_HOUR;
            float temp_range = PEAK_TEMP - LOW_TEMP;
            t_target = PEAK_TEMP - (hours_past_peak / total_ramp_hours) * temp_range;
          }

          // === 3. DETERMINE DESIRED STATES ===
          bool pump_wants_to_be_on = id(pump_relay).state;
          bool fan_wants_to_be_on = id(fan_relay).state;
          bool cooler_wants_to_be_on = id(cooler_relay).state;
          bool lamp_wants_to_be_on = id(lamp_relay).state;

          if (t > t_target + 1.0) {
            cooler_wants_to_be_on = true;
          } else if (t < t_target - 1.0) {
            cooler_wants_to_be_on = false;
          }
          
          if (t < t_target - 1.0) {
            lamp_wants_to_be_on = true;
          } else if (t > t_target + 1.0) {
            lamp_wants_to_be_on = false;
          }

          if (is_evening_spike) {
            pump_wants_to_be_on = (h < 90.0);
            fan_wants_to_be_on = false;
            id(high_humidity_counter) = 0;
          
          } else if (is_day) {
            if (h < 50.0) {
              pump_wants_to_be_on = true;
            } else if (h > 60.0) {
              pump_wants_to_be_on = false;
            }
            
            if (h > 75.0) {
              id(high_humidity_counter) = id(high_humidity_counter) + 1;
              if (id(high_humidity_counter) >= 3) fan_wants_to_be_on = true;
            } else if (h < 70.0) {
              id(high_humidity_counter) = 0;
              fan_wants_to_be_on = false;
            }
          
          } else {
            if (h < 70.0) {
              pump_wants_to_be_on = true;
            } else if (h > 75.0) {
              pump_wants_to_be_on = false;
            }

            if (h > 95.0) {
              id(high_humidity_counter) = id(high_humidity_counter) + 1;
              if (id(high_humidity_counter) >= 3) fan_wants_to_be_on = true;
            } else if (h < 90.0) {
              id(high_humidity_counter) = 0;
              fan_wants_to_be_on = false;
            }
          }

          // === 4. APPLY PRIORITIES ===
          if (pump_wants_to_be_on && !is_evening_spike) { 
              fan_wants_to_be_on = false;
              id(high_humidity_counter) = 0;
          }
          if (cooler_wants_to_be_on) {
              lamp_wants_to_be_on = false;
          }
          if (cooler_wants_to_be_on) {
              fan_wants_to_be_on = false;
              id(high_humidity_counter) = 0;
          }
          if (pump_wants_to_be_on && cooler_wants_to_be_on) {
              bool emergency_temp_override = (is_day && t > 26.0) || (is_night && t > 20.0);
              if (!emergency_temp_override) {
                  cooler_wants_to_be_on = false; 
              }
          }

          // === 5. EXECUTE FINAL STATES ===
          if (pump_wants_to_be_on) id(pump_relay).turn_on();
          else id(pump_relay).turn_off();

          if (fan_wants_to_be_on) id(fan_relay).turn_on();
          else id(fan_relay).turn_off();

          if (cooler_wants_to_be_on) id(cooler_relay).turn_on();
          else id(cooler_relay).turn_off();

          if (lamp_wants_to_be_on) id(lamp_relay).turn_on();
          else id(lamp_relay).turn_off();
